--1.1 TẠO CSDL QLDA
CREATE DATABASE QLSV;
USE QLSV;
--1.2 Tạo 6 bảng
CREATE TABLE KHOA
(
	MaKhoa VARCHAR(10) NOT NULL PRIMARY KEY,
	TenKhoa NVARCHAR(50) NOT NULL,
	SL_CBGD SMALLINT NOT NULL
);
CREATE TABLE GIAOVIEN
(
	MaGV VARCHAR(5) NOT NULL PRIMARY KEY,
	TenGV NVARCHAR(50) NOT NULL,
	MaKhoa VARCHAR(10) FOREIGN KEY REFERENCES KHOA(MaKhoa)
);
CREATE TABLE MONHOC
(
	MaMH VARCHAR(5) NOT NULL PRIMARY KEY,
	TenMH NVARCHAR(5) NOT NULL,
	SoTC smallint NOT NULL
);
CREATE TABLE SINHVIEN
(
	MSSV VARCHAR(5) NOT NULL PRIMARY KEY,
	Ten NVARCHAR(50) NOT NULL,
	GioiTinh VARCHAR(5) NOT NULL,
	DiaChi NVARCHAR(20) NOT NULL,
	DienThoai VARCHAR(20),
	MaKhoa VARCHAR(10) FOREIGN KEY REFERENCES KHOA(MaKhoa)
);
CREATE TABLE GIANGDAY
(
	MaKhoaHoc VARCHAR(5) NOT NULL PRIMARY KEY,
	MaGV VARCHAR(5) FOREIGN KEY REFERENCES GIAOVIEN(MaGV),
	MaMH VARCHAR(5) FOREIGN KEY REFERENCES MONHOC(MaMH),
	HocKy SMALLINT NOT NULL,
	Nam INT NOT NULL,
);
CREATE TABLE KETQUA
(
	MaSV VARCHAR(5) FOREIGN KEY REFERENCES SINHVIEN(MSSV),
	MaKhoaHoc VARCHAR(5) FOREIGN KEY REFERENCES GIANGDAY(MaKhoaHoc),
	Diem DECIMAL(3,1) NOT NULL,
	CONSTRAINT pk_ketqua PRIMARY KEY (MaSV, MaKhoaHoc)
);