CREATE DATABASE QLKTX;
USE QLKTX;
CREATE TABLE PHANKHU
(
	MaKhu VARCHAR(5) NOT NULL PRIMARY KEY,
	DiaChi NVARCHAR(50) NOT NULL,
	SoLuongSinhVien SMALLINT NOT NULL
);
CREATE TABLE DICHVU
(
	MaDV VARCHAR(5) NOT NULL PRIMARY KEY,
	TenDichVu NVARCHAR(25) NOT NULL
);
CREATE TABLE PHONG
(
	MaPhong VARCHAR(5) NOT NULL,
	MaKhu VARCHAR(5) NOT NULL FOREIGN KEY REFERENCES PHANKHU(MaKhu),
	TrangThaiPhong NVARCHAR(10) NOT NULL,
	SoLuongToiDa SMALLINT NOT NULL,
	PRIMARY KEY (MaPhong,MaKhu)
);
CREATE TABLE SINHVIEN
(
	MaSV VARCHAR(5) NOT NULL PRIMARY KEY,
	Ho NVARCHAR(10) NOT NULL,
	Ten NVARCHAR(10) NOT NULL,
	NgaySinh DATE NOT NULL,
	GioiTinh NVARCHAR(3) NOT NULL,
	SoDienThoai VARCHAR(15) NOT NULL,
	Email VARCHAR(100) NOT NULL,
	DiaChi NVARCHAR(50) NOT NULL,
	MaPhong VARCHAR(5) NOT NULL,
	MaKhu VARCHAR(5) NOT NULL,
	FOREIGN KEY (MaPhong,MaKhu) REFERENCES PHONG(MaPhong,MaKhu)
);
CREATE TABLE QUANTRI
(
	MaQT VARCHAR(5) NOT NULL PRIMARY KEY,
	Ho NVARCHAR(10) NOT NULL,
	TEN NVARCHAR(10) NOT NULL,
	SoDienThoai VARCHAR(15) NOT NULL,
	MaKhu VARCHAR(5) NOT NULL FOREIGN KEY REFERENCES PHANKHU(MaKhu)
);
CREATE TABLE HOPDONG
(
	MAHD VARCHAR(5) NOT NULL PRIMARY KEY,
	MaSV VARCHAR(5) NOT NULL FOREIGN KEY REFERENCES SINHVIEN(MaSV),
	NgayApDung DATE NOT NULL,
	NgayHetHan DATE NOT NULL,
	GiaPhong DECIMAL(8,2) NOT NULL,
	TrangThaiHopDong NVARCHAR(20) NOT NULL,
);
CREATE TABLE DANGKYDICHVU
(
	MaDK VARCHAR(5) NOT NULL PRIMARY KEY,
	MaDV VARCHAR(5) NOT NULL FOREIGN KEY REFERENCES DICHVU(MaDV),
	MaSV VARCHAR(5) NOT NULL FOREIGN KEY REFERENCES SINHVIEN(MaSV),
	MaKhu VARCHAR(5) NOT NULL,
	MaPhong VARCHAR(5) NOT NULL,
	ThoiGianBatDau DATETIME NOT NULL,
	ThoiGianKetThuc DATETIME NOT NULL,
	FOREIGN KEY(MaPhong,MaKhu) REFERENCES PHONG(MaPhong,MaKhu)
);
CREATE TABLE DONGIA
(
	MaDV VARCHAR(5) NOT NULL PRIMARY KEY,
	FOREIGN KEY(MaDV) REFERENCES DICHVU(MaDV),
	DonGia DECIMAL(8,2) NOT NULL,
	DonViTinh NVARCHAR(20) NOT NULL
);
CREATE TABLE HOADON
(
	MaHD VARCHAR(5) NOT NULL PRIMARY KEY,
	NgayLap DATE NOT NULL,
	TongTien DECIMAL(8,2) NOT NULL,
	MaPhong VARCHAR(5) NOT NULL,
	MaKhu VARCHAR(5) NOT NULL,
	TrangThaiThanhToan NVARCHAR(20) NOT NULL,
	MaDV VARCHAR(5) NOT NULL FOREIGN KEY REFERENCES DICHVU(MaDV),
	FOREIGN KEY(MaPhong,MaKhu) REFERENCES PHONG(MaPhong,MaKhu)
);